name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧹 Chores'
    label: 'chore'
  - title: '📚 Documentation'
    label: 'docs'
  - title: '💥 Breaking Changes'
    label: 'breaking'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'chore'
      - 'docs'
  default: patch

template: |
  ## Changes

  $CHANGES
