"""Type stubs for gsyncio package."""

import asyncio
import enum
import logging
import types
from collections.abc import AsyncGenerator, AsyncIterator, Callable
from typing import Any, Self

from gsyncio.exceptions import (
    ChannelClosedError,
    GsyncioError,
    ThreadPoolClosedError,
    TimeoutError,
    WouldBlock,
)

__all__ = [
    "AsyncContext",
    "AsyncOnce",
    "AsyncRWMutex",
    "AsyncWaitGroup",
    "Barrier",
    "BarrierWaitResult",
    "CancelScope",
    "CapacityLimiter",
    "ChannelClosedError",
    "Condition",
    "ConnectionPinningServer",
    "Event",
    "EventLoopThreadPool",
    "FastChannel",
    "GsyncioASGIWorker",
    "GsyncioError",
    "Lock",
    "PoolOptions",
    "Semaphore",
    "TaskGroup",
    "TaskHandle",
    "TaskStatus",
    "ThreadPoolClosedError",
    "TimeoutError",
    "WouldBlock",
    "__version__",
    "checkpoint",
    "create_pool",
    "current_effective_deadline",
    "fail_after",
    "fail_at",
    "get_logger",
    "move_on_after",
    "move_on_at",
    "run_in_pool",
    "select_channel",
    "set_log_level",
]

__version__: str

# -- PoolOptions ----------------------------------------------------------

class PoolOptions:
    num_threads: int
    loop_factory: Callable[[], asyncio.AbstractEventLoop] | None

    def __init__(
        self,
        num_threads: int = 0,
        loop_factory: Callable[[], asyncio.AbstractEventLoop] | None = None,
    ) -> None: ...

# -- CancelScope ----------------------------------------------------------

class CancelScope:
    def __init__(self, deadline: float = float("inf"), shield: bool = False) -> None: ...
    @property
    def cancel_called(self) -> bool: ...
    @property
    def deadline(self) -> float: ...
    @deadline.setter
    def deadline(self, value: float) -> None: ...
    @property
    def shield(self) -> bool: ...
    @shield.setter
    def shield(self, value: bool) -> None: ...
    @property
    def cancelled_caught(self) -> bool: ...
    def cancel(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> bool | None: ...

# -- EventLoopThreadPool --------------------------------------------------

class EventLoopThreadPool:
    num_threads: int

    def __init__(
        self,
        options: PoolOptions | None = None,
        num_threads: int | None = None,
        loop_factory: Callable[[], asyncio.AbstractEventLoop] | None = None,
    ) -> None: ...
    @property
    def is_running(self) -> bool: ...
    def get_metrics(self) -> dict[str, Any]: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    async def abort(self) -> None: ...
    async def wait_closed(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...
    def submit(
        self,
        target: Callable[..., Any] | Any,
        *args: Any,
        pin_to: asyncio.AbstractEventLoop | int | None = None,
        cancel_scope: CancelScope | None = None,
        **kwargs: Any,
    ) -> asyncio.Future[Any]: ...

# -- FastChannel ----------------------------------------------------------

class FastChannel:
    def __init__(self, maxsize: int = 0) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def maxsize(self) -> int: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    async def send(self, item: Any) -> None: ...
    async def recv(self, timeout: float | None = None) -> Any: ...
    def try_send(self, item: Any) -> bool: ...
    def try_recv(self) -> Any: ...
    def qsize(self) -> int: ...
    def __aiter__(self) -> AsyncIterator[Any]: ...
    async def __anext__(self) -> Any: ...

# -- select_channel -------------------------------------------------------

async def select_channel(
    *channels: Any, timeout: float | None = None, default: Any = ...
) -> Any: ...

# -- AsyncContext ---------------------------------------------------------

class AsyncContext:
    @property
    def parent(self) -> AsyncContext | None: ...
    def __init__(self, parent: AsyncContext | None = None) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...
    def submit(
        self,
        pool: EventLoopThreadPool,
        target: Callable[..., Any],
        *args: Any,
        **kwargs: Any,
    ) -> asyncio.Future[Any]: ...
    def cancel(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> None: ...

# -- AsyncWaitGroup -------------------------------------------------------

class AsyncWaitGroup:
    def __init__(self) -> None: ...
    def add(self, delta: int = 1) -> None: ...
    def done(self) -> None: ...
    def holding(self) -> AsyncGenerator[None]: ...
    def wrap(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def track(self, coro: Any) -> Any: ...
    async def wait(self) -> None: ...

# -- AsyncOnce ------------------------------------------------------------

class AsyncOnce:
    def __init__(self) -> None: ...
    async def do(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...

# -- AsyncRWMutex ---------------------------------------------------------

class AsyncRWMutex:
    def __init__(self) -> None: ...
    def reader(self) -> AsyncGenerator[None]: ...
    def writer(self) -> AsyncGenerator[None]: ...

# -- ConnectionPinningServer ----------------------------------------------

class ConnectionPinningServer:
    pool: EventLoopThreadPool
    host: str
    port: int
    handler: Callable[[asyncio.StreamReader, asyncio.StreamWriter], Any] | None

    def __init__(
        self,
        pool: EventLoopThreadPool,
        host: str = "127.0.0.1",
        port: int = 0,
        handler: Callable[[asyncio.StreamReader, asyncio.StreamWriter], Any] | None = None,
    ) -> None: ...
    @property
    def is_running(self) -> bool: ...
    async def start(
        self,
        handler: Callable[[asyncio.StreamReader, asyncio.StreamWriter], Any] | None = None,
    ) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...

# -- GsyncASGIWorker ------------------------------------------------------

class GsyncioASGIWorker:
    app: Callable[..., Any]
    pool: EventLoopThreadPool
    host: str
    port: int

    def __init__(
        self,
        app: Callable[..., Any],
        pool: EventLoopThreadPool,
        host: str = "127.0.0.1",
        port: int = 0,
    ) -> None: ...
    @property
    def is_running(self) -> bool: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...

# -- Lock -----------------------------------------------------------------

class Lock:
    def __init__(self) -> None: ...
    @property
    def locked(self) -> bool: ...
    @property
    def owner(self) -> asyncio.Task[Any] | None: ...
    async def acquire(self) -> None: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> bool | None: ...

# -- Semaphore ------------------------------------------------------------

class Semaphore:
    def __init__(self, max_value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @property
    def max_value(self) -> int: ...
    async def acquire(self) -> None: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object | None,
    ) -> bool | None: ...

# -- CapacityLimiter ------------------------------------------------------

class CapacityLimiter:
    def __init__(self, total_tokens: float) -> None: ...
    @property
    def total_capacity(self) -> int: ...
    @property
    def available_capacity(self) -> int: ...
    @property
    def total_tokens(self) -> float: ...
    @total_tokens.setter
    def total_tokens(self, value: float) -> None: ...
    @property
    def available_tokens(self) -> float: ...
    @property
    def borrowed_tokens(self) -> float: ...
    def snapshot(self) -> tuple[float, float, float]: ...
    async def acquire(self) -> None: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object | None,
    ) -> bool | None: ...

# -- Event ----------------------------------------------------------------

class Event:
    def __init__(self) -> None: ...
    def is_set(self) -> bool: ...
    def set(self) -> None: ...
    async def wait(self) -> None: ...

# -- Condition ------------------------------------------------------------

class Condition:
    def __init__(self, lock: Lock | None = None) -> None: ...
    async def acquire(self) -> None: ...
    def release(self) -> None: ...
    async def wait(self) -> None: ...
    async def wait_for(self, predicate: Callable[[], Any]) -> Any: ...
    def notify(self, n: int = 1) -> None: ...
    def notify_all(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> bool | None: ...

# -- Barrier --------------------------------------------------------------

class BarrierWaitResult:
    parties: int
    index: int

    def __init__(self, parties: int, index: int = ...) -> None: ...
    @property
    def is_leader(self) -> bool: ...

class Barrier:
    def __init__(self, parties: int) -> None: ...
    @property
    def parties(self) -> int: ...
    @property
    def broken(self) -> bool: ...
    @property
    def n_waiting(self) -> int: ...
    async def wait(self) -> BarrierWaitResult: ...
    def abort(self) -> None: ...
    def reset(self) -> None: ...

# -- TaskGroup / TaskHandle / TaskStatus ----------------------------------

class _TaskStatus(enum.Enum):
    PENDING = ...
    STARTED = ...
    FINISHED = ...

class TaskStatus:
    def __init__(self) -> None: ...
    def started(self) -> None: ...

class TaskHandle:
    @property
    def status(self) -> _TaskStatus: ...
    @property
    def result(self) -> Any: ...
    @property
    def exception(self) -> BaseException | None: ...
    def __await__(self) -> Any: ...

class TaskGroup:
    def __init__(self, name: str | None = None) -> None: ...
    def start_soon(self, coro_fn: Callable[..., Any], *args: Any) -> TaskHandle: ...
    async def start(self, coro_fn: Callable[..., Any], *args: Any) -> TaskHandle: ...
    def cancel_all(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> bool | None: ...

# -- Top-level convenience functions ---------------------------------------

async def create_pool(
    num_threads: int = 0,
    options: PoolOptions | None = None,
    **kwargs: Any,
) -> EventLoopThreadPool: ...
async def run_in_pool(coro: Any, *args: Any, num_threads: int = 0, **kwargs: Any) -> Any: ...
async def checkpoint() -> None: ...
def current_effective_deadline() -> float: ...
def fail_after(seconds: float) -> CancelScope: ...
def move_on_after(seconds: float) -> CancelScope: ...
def fail_at(deadline: float) -> CancelScope: ...
def move_on_at(deadline: float) -> CancelScope: ...
def get_logger(name: str | None = None) -> logging.LoggerAdapter[Any]: ...
def set_log_level(level: int) -> None: ...
