"""Type stubs for native Rust extension _gsyncio_core."""

from typing import Any

class AtomicMetrics:
    def __init__(self, num_threads: int) -> None: ...
    def inc_active(self, index: int) -> None: ...
    def dec_active(self, index: int) -> None: ...
    def get_active(self, index: int) -> int: ...
    def get_completed(self, index: int) -> int: ...
    def inc_global_pull(self, index: int) -> None: ...
    def get_global_pull(self, index: int) -> int: ...
    def inc_park(self, index: int) -> None: ...
    def get_park(self, index: int) -> int: ...
    def set_injection_queue_depth(self, index: int, depth: int) -> None: ...
    def get_injection_queue_depth(self, index: int) -> int: ...
    def inc_remote_schedule(self, index: int) -> None: ...
    def get_remote_schedule(self, index: int) -> int: ...

class NativeWorkerPool:
    def __init__(self, num_threads: int) -> None: ...
    def close(self) -> None: ...
    def set_metrics(self, metrics: AtomicMetrics) -> None: ...
    def is_closed(self) -> bool: ...
    def is_drained(self) -> bool: ...
    def push_global(self, task: Any) -> None: ...
    def push_local(self, index: int, task: Any) -> None: ...
    def pop_work(self, index: int) -> Any | None: ...

class FastChannel:
    def __init__(self, maxsize: int) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def try_send(self, item: Any) -> bool: ...
    # Returns (has_item, item): the bool distinguishes "empty" from a None payload.
    def try_recv(self) -> tuple[bool, Any]: ...
    def qsize(self) -> int: ...

class RawAsyncWaitGroup:
    def __init__(self) -> None: ...
    def add(self, delta: int) -> list[tuple[Any, Any]] | None: ...
    def done(self) -> list[tuple[Any, Any]] | None: ...
    def register_waiter(self, waiter: tuple[Any, Any]) -> bool: ...
    def unregister_waiter(self, fut: Any) -> bool: ...
